### ISSUE TITLE
5.6 IDL name is wrong

### ISSUE THREAD

**Issue by zacc** [browserobo/WebGPIO#1]
The name reads `MIDIMessageEventInit`
https://github.com/browserobo/WebGPIO/commit/18b37b2a9dcebece9baa403d918cde1f6a502552#diff-eacf331f0ffc35d4b482f1d15a887d3bR705

**Comment by zacc** [comment]
https://github.com/browserobo/WebGPIO/pull/3

**Comment by satakagi** [comment]
Thanks!
